language: node_js
node_js:
  - "8"

before_script:
  - 'yarn build'
  - 'yarn build-storybook'

deploy:
  provider: pages
  local_dir: './storybook-static'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master